// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Terapias_rehabilitaciones.Data;

#nullable disable

namespace Terapias_rehabilitaciones.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430214359_CorregirPlanTratamiento")]
    partial class CorregirPlanTratamiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPlan")
                        .HasColumnType("integer");

                    b.Property<int>("PuntajeProgreso")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdPlan");

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StockActual")
                        .HasColumnType("integer");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.PlanTratamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaFinEstimada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPaciente");

                    b.ToTable("Planes");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Sesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer");

                    b.Property<int>("IdTerapeuta")
                        .HasColumnType("integer");

                    b.Property<int>("IdTipoTerapia")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PacienteId")
                        .HasColumnType("integer");

                    b.Property<int?>("TerapeutaId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoTerapiaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.HasIndex("TerapeutaId");

                    b.HasIndex("TipoTerapiaId");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Terapeuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Terapeutas");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.TipoTerapia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TiposTerapia");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.UsoInsumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadUsada")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("integer");

                    b.Property<int>("IdSesion")
                        .HasColumnType("integer");

                    b.Property<int>("InsumoId")
                        .HasColumnType("integer");

                    b.Property<int>("SesionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsumoId");

                    b.HasIndex("SesionId");

                    b.ToTable("UsoInsumos");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Evaluacion", b =>
                {
                    b.HasOne("Terapias_rehabilitaciones.Models.PlanTratamiento", "Plan")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.PlanTratamiento", b =>
                {
                    b.HasOne("Terapias_rehabilitaciones.Models.Paciente", "Paciente")
                        .WithMany("Planes")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Sesion", b =>
                {
                    b.HasOne("Terapias_rehabilitaciones.Models.Paciente", "Paciente")
                        .WithMany("Sesiones")
                        .HasForeignKey("PacienteId");

                    b.HasOne("Terapias_rehabilitaciones.Models.Terapeuta", "Terapeuta")
                        .WithMany("Sesiones")
                        .HasForeignKey("TerapeutaId");

                    b.HasOne("Terapias_rehabilitaciones.Models.TipoTerapia", "TipoTerapia")
                        .WithMany("Sesiones")
                        .HasForeignKey("TipoTerapiaId");

                    b.Navigation("Paciente");

                    b.Navigation("Terapeuta");

                    b.Navigation("TipoTerapia");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.UsoInsumo", b =>
                {
                    b.HasOne("Terapias_rehabilitaciones.Models.Insumo", "Insumo")
                        .WithMany("UsoInsumos")
                        .HasForeignKey("InsumoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terapias_rehabilitaciones.Models.Sesion", "Sesion")
                        .WithMany("UsoInsumos")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insumo");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Insumo", b =>
                {
                    b.Navigation("UsoInsumos");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Paciente", b =>
                {
                    b.Navigation("Planes");

                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.PlanTratamiento", b =>
                {
                    b.Navigation("Evaluaciones");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Sesion", b =>
                {
                    b.Navigation("UsoInsumos");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.Terapeuta", b =>
                {
                    b.Navigation("Sesiones");
                });

            modelBuilder.Entity("Terapias_rehabilitaciones.Models.TipoTerapia", b =>
                {
                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
